# Generated by Django 2.1.4 on 2018-12-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='number_of_pages',
            field=models.IntegerField(default=1),
        ),
    ]
