# Generated by Django 2.1.5 on 2019-01-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0004_auto_20190115_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(),
        ),
    ]
