# Generated by Django 2.1.5 on 2019-01-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0005_auto_20190115_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='page',
        ),
        migrations.AddField(
            model_name='folder',
            name='full',
            field=models.CharField(default='Unknown', max_length=191),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='file_name',
            field=models.CharField(default='Unknown', max_length=191),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
