# Generated by Django 2.1.5 on 2019-01-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0007_auto_20190118_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.AddField(
            model_name='document',
            name='author_organization',
            field=models.ManyToManyField(blank=True, related_name='author_organization', to='dj_comp_hist.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='author_person',
            field=models.ManyToManyField(blank=True, related_name='author_person', to='dj_comp_hist.Person'),
        ),
    ]
