# Generated by Django 2.1.5 on 2019-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0008_auto_20190118_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='recipient',
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_organization',
            field=models.ManyToManyField(blank=True, related_name='recipient_organization', to='dj_comp_hist.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_person',
            field=models.ManyToManyField(blank=True, related_name='recipient_person', to='dj_comp_hist.Person'),
        ),
    ]
