# Generated by Django 2.1.5 on 2019-01-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0009_auto_20190118_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=191),
        ),
    ]
