# Generated by Django 2.1.5 on 2019-01-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0010_auto_20190118_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='page',
            field=models.OneToOneField(blank=True, on_delete=models.SET(None), to='dj_comp_hist.Page'),
        ),
    ]
