# Generated by Django 2.1.5 on 2019-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0011_auto_20190118_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=191),
        ),
    ]
