# Generated by Django 2.1.5 on 2019-01-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0013_auto_20190123_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.CharField(blank=True, max_length=191),
        ),
    ]
