# Generated by Django 2.1.5 on 2019-01-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0016_auto_20190128_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='file_name',
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_path',
            field=models.CharField(max_length=191),
        ),
    ]
