# Generated by Django 2.1.5 on 2019-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0017_auto_20190128_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='png_pages'),
        ),
    ]
