# Generated by Django 2.1.5 on 2019-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0018_auto_20190131_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
