# Generated by Django 2.1.5 on 2019-02-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0019_auto_20190212_1014'),
        ('dj_comp_hist', '0019_auto_20190214_1830'),
    ]

    operations = [
    ]
