# Generated by Django 2.1.5 on 2019-02-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0020_merge_20190222_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_path',
        ),
    ]
