# Generated by Django 2.1.5 on 2019-02-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0020_merge_20190222_1428'),
        ('dj_comp_hist', '0020_merge_20190222_2120'),
        ('dj_comp_hist', '0020_merge_20190222_1555'),
    ]

    operations = [
    ]
