# Generated by Django 2.1.5 on 2019-02-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0021_merge_20190225_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_path',
        ),
    ]
