# Generated by Django 2.1.8 on 2019-04-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('type', models.CharField(blank=True, max_length=191)),
                ('number_of_pages', models.IntegerField(default=1)),
                ('first_page', models.IntegerField(default=0)),
                ('last_page', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=191)),
                ('file_name', models.CharField(max_length=191, unique=True)),
                ('text', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('full', models.CharField(max_length=191)),
                ('number', models.IntegerField(default=0)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=191)),
                ('name', models.CharField(blank=True, max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=191)),
                ('last', models.CharField(blank=True, max_length=191)),
                ('organization', models.ManyToManyField(blank=True, to='archives.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(blank=True, on_delete=models.SET(None), to='archives.Page')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='author_organization',
            field=models.ManyToManyField(blank=True, related_name='author_organization', to='archives.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='author_person',
            field=models.ManyToManyField(blank=True, related_name='author_person', to='archives.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='cced_organization',
            field=models.ManyToManyField(blank=True, related_name='cced_organization', to='archives.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='cced_person',
            field=models.ManyToManyField(blank=True, related_name='cced_person', to='archives.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_organization',
            field=models.ManyToManyField(blank=True, related_name='recipient_organization', to='archives.Organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_person',
            field=models.ManyToManyField(blank=True, related_name='recipient_person', to='archives.Person'),
        ),
    ]
