# Generated by Django 2.1.5 on 2019-04-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
