# Generated by Django 2.1.5 on 2019-04-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20190429_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='slug',
            field=models.SlugField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=191, unique=True),
        ),
    ]
