# Generated by Django 2.1.8 on 2019-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20190429_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['full']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last', 'first']},
        ),
    ]
