# Generated by Django 2.1.8 on 2019-05-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20190509_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['box__number', 'number', 'full']},
        ),
    ]
