# Generated by Django 2.1.8 on 2019-05-24 11:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20190509_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['box__number', 'number', 'full']},
        ),
        migrations.AddField(
            model_name='document',
            name='text_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='person',
            name='first',
            field=models.CharField(blank=True, db_index=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='person',
            name='last',
            field=models.CharField(blank=True, db_index=True, max_length=191),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_search_vector'], name='archives_do_text_se_924bfb_gin'),
        ),
    ]
