# Generated by Django 2.1.5 on 2019-03-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_comp_hist', '0023_auto_20190315_1754'),
        ('dj_comp_hist', '0023_auto_20190315_1837'),
    ]

    operations = [
    ]
