"""
Django settings for the dh@mit computational history project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .settings_base import *

print('reading production settings!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

SECRET_KEY = os.environ['DJANGO_SECRET_KEY'] # currently set in venv

ALLOWED_HOSTS = [
    'comphist.digitalhumanitiesmit.org',
    'comphist.dhlab.mit.edu',
]

ADMINS = ['rahmed@mit.edu'] # Django will email Ryaan on internal server errors


# logging via sentry
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
sentry_sdk.init(
    dsn="https://7e07eb1932794acb815991163d9195b5@sentry.io/1462136",
    integrations=[DjangoIntegration()]
)

